name: Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deployment/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Notification
        run: |
          echo "Deployment files updated."
          echo "Manual deployment required on VM."
          echo "See deployment/README.md for instructions."
